### PR TITLE
fix: list widget data loss

### PR DESCRIPTION
**Pull request by kara-todd**
for #926

### CODE REVIEW

**Comment by kara-todd** [comment]
I'm not sure if there is a side-effect to changing the set function. The tests seem to pass when I ran it and it resolved the issue I was having.

**Comment by kara-todd** [comment]
superseded by #930

**Comment by KaneFreeman** [comment]
Interesting. Did that fix the issue? For `v4.0.0` (in the `next` branch, coming to beta soon) I actually did switch to using the lodash `set` function everywhere. I'll need to test to see if that resolves the issue, as #930 might be unneccessary.

**Comment by kara-todd** [comment]
Yes, it did fix it for me in local testing. I also ran the test suite and everything passed... but I wasn't sure if it introduced any side effects. 😅 

I had assumed the key just wasn't being parsed properly because I was able to see the correct value data and path reach the `set` function. This fix you made in #940 also resolved the issue though... So maybe the key parse wasn't the root problem?

**Pull request closed without merging**
